#pragma once

#define MASTER_LEFT

#define USB_POLLING_INTERVAL_MS 1

#define RGB_MATRIX_SPLIT { 19, 19 }
#define RGB_MATRIX_MAXIMUM_LED_COUNT 38
#define OS_DETECTION_SINGLE_REPORT
#define OS_DETECTION_KEYBOARD_RESET
